---
- name: test if iptables_ssh_port is set correctly
  assert:
    that:
      - iptables_ssh_port is defined
      - iptables_ssh_port | int > 0
      - iptables_ssh_port | int <= 65535
    fail_msg: "'iptables_ssh_port' must be between 1 and 65535"
    quiet: true
