---
- name: Save iptables rules [RedHat] [ipv4]
  community.general.iptables_state:
    ip_version: "ipv4"
    state: saved
    path: "/etc/sysconfig/iptables"
  when: ansible_os_family == "RedHat"
  listen: save_iptables_rules_redhat_ipv4

- name: Save iptables rules [Debian] [ipv4]
  community.general.iptables_state:
    ip_version: "ipv4"
    state: saved
    path: "/etc/iptables/rules.v4"
  when: ansible_os_family == "Debian"
  listen: save_iptables_rules_debian_ipv4

- name: Save iptables rules [RedHat] [ipv6]
  community.general.iptables_state:
    ip_version: "ipv6"
    state: saved
    path: "/etc/sysconfig/ip6tables"
  when: ansible_os_family == "RedHat"
  listen: save_iptables_rules_redhat_ipv6

- name: Save iptables rules [Debian] [ipv6]
  community.general.iptables_state:
    ip_version: "ipv6"
    state: saved
    path: "/etc/iptables/rules.v6"
  when: ansible_os_family == "Debian"
  listen: save_iptables_rules_debian_ipv6
